# Generational Shifts in Malaysia: A Look at Population Trends by Age and State.
This project will explore population data by age and state in Malaysia. The analysis can reveal trends in population growth, aging, and potential implications for social services and economic planning.

In [6]:
import pandas as pd
import matplotlib as plt
# add more if required

In [4]:
# PopulationDataLoader class
class PopulationDataLoader:

    # Initializes the PopulationDataLoader with the URL of the Parquet file.
    def __init__(self, url):
        self.url = url
        self.df = None

    # Loads the population data from the specified URL into a pandas DataFrame.
    def load_data(self):  
        self.df = pd.read_parquet(self.url)
        return self.df

In [5]:
URL = "https://storage.dosm.gov.my/population/population_state.parquet"
loader = PopulationDataLoader(URL)
df = loader.load_data()
df

,state,date,sex,age,ethnicity,population
0,Johor,1970-01-01,both,overall,overall,1325.6
1,Johor,1970-01-01,both,0-4,overall,210.1
2,Johor,1970-01-01,both,5-9,overall,215.7
3,Johor,1970-01-01,both,10-14,overall,192.2
4,Johor,1970-01-01,both,15-19,overall,152.8
...,...,...,...,...,...,...
250906,W.P. Putrajaya,2023-01-01,male,85+,bumi_other,0.0
250907,W.P. Putrajaya,2023-01-01,male,85+,chinese,0.0
250908,W.P. Putrajaya,2023-01-01,male,85+,indian,0.0
250909,W.P. Putrajaya,2023-01-01,male,85+,other_citizen,0.0
250910,W.P. Putrajaya,2023-01-01,male,85+,other_noncitizen,0.0